/* VANES AI frontend runtime — one authoritative UI layer. */
(function(){
'use strict';
const subjects=[
['Kiswahili','O-Level','Sarufi, fasihi, ufahamu na uandishi'],['English Language','O-Level','Grammar, comprehension, writing and communication'],['Basic Mathematics','O-Level','Numbers, algebra, geometry, statistics and problem solving'],['Basic Applied Mathematics','O-Level','Commercial arithmetic, graphs, statistics and applications'],['History','O-Level','Tanzania, Africa, colonialism, nationalism and world history'],['Geography','O-Level','Map work, climate, population, resources, development and fieldwork'],['Chemistry','O-Level','Atomic structure, bonding, reactions, acids, bases and organic chemistry'],['Physics','O-Level','Measurement, mechanics, heat, waves, electricity and practical physics'],['Biology','O-Level','Cells, nutrition, transport, reproduction, genetics, ecology and health'],['Civics','O-Level','Citizenship, democracy, human rights, government and governance'],['Information and Computer Studies','O-Level','Computer systems, information, networks and digital skills'],['Commerce','O-Level','Trade, business, banking, insurance, transport and marketing'],['Bookkeeping','O-Level','Double entry, journals, ledgers, trial balance and final accounts'],['Agriculture','O-Level','Soils, crops, livestock, farm management and sustainable agriculture'],['Food and Nutrition','O-Level','Nutrition, food preparation, hygiene and meal planning'],['Fine Art','O-Level','Drawing, design, colour, visual communication and art appreciation'],['Music','O-Level','Music theory, notation, performance and appreciation'],['French','O-Level','French grammar, vocabulary, comprehension and communication'],['Arabic','O-Level','Arabic language, grammar, reading and communication'],['Bible Knowledge','O-Level','Biblical studies, interpretation and Christian knowledge'],['Islamic Knowledge','O-Level',"Qur'an, Hadith, Islamic history and values"],['Physical Education','O-Level','Fitness, health, games and sports'],['Economics','O-Level','Economic concepts, markets, production and development'],['Business Studies','O-Level','Entrepreneurship, management, marketing and business planning'],['Computer Applications','O-Level','Word processing, spreadsheets, presentations and data management'],
['Advanced Mathematics','A-Level','Functions, algebra, trigonometry, calculus, vectors, probability and statistics'],['Economics','A-Level','Microeconomics, macroeconomics, national income, trade and development'],['History','A-Level','Advanced historical analysis, Africa, Tanzania and global change'],['Geography','A-Level','Advanced physical and human geography, development and fieldwork'],['Physics','A-Level','Mechanics, electricity, waves, thermal physics and modern physics'],['Chemistry','A-Level','Physical, inorganic and organic chemistry with practical work'],['Biology','A-Level','Advanced genetics, physiology, ecology, evolution and practical biology'],['General Studies','A-Level','Critical thinking, communication, society, science and current issues'],['Computer Science','A-Level','Algorithms, programming, databases, networks and cybersecurity'],['Accountancy','A-Level','Financial accounting, partnerships, companies, analysis and budgeting'],['Commerce','A-Level','Business systems, trade, finance, marketing and management'],['Business Studies','A-Level','Management, marketing, finance, human resources and strategy'],['Computer Applications','A-Level','Advanced productivity, data analysis and information management']
].map(x=>({name:x[0],level:x[1],lesson:x[2],description:x[2]+'. VANES can explain, practise, analyse and revise this area.'}));
const topics={
'Kiswahili':['Sarufi','Fasihi simulizi','Fasihi andishi','Ufahamu','Uandishi','Mawasiliano','Msamiati'],
'English Language':['Grammar','Comprehension','Vocabulary','Writing','Oral communication','Summary writing','Functional writing'],
'Basic Mathematics':['Numbers','Algebra','Equations','Geometry','Mensuration','Trigonometry','Statistics','Probability','Sets','Sequences','Coordinate geometry','Financial mathematics'],
'Basic Applied Mathematics':['Commercial arithmetic','Ratio and proportion','Percentages','Rates','Graphs','Statistics','Measurement','Financial mathematics','Linear programming'],
'Advanced Mathematics':['Algebra','Functions','Polynomials','Sequences and series','Trigonometry','Vectors','Matrices','Differentiation','Integration','Differential equations','Probability','Statistics'],
'History':['Pre-colonial African societies','Slave trade','Colonialism','Nationalism','African independence','Tanzania and Tanganyika','World Wars','Cold War','Post-independence Africa'],
'Geography':['Map reading','Weather and climate','Geomorphology','Soils','Vegetation','Water resources','Population','Settlement','Agriculture','Industry','Transport','Tourism','Environment','Fieldwork','Development'],
'Chemistry':['Matter','Atomic structure','Periodic table','Chemical bonding','Formulae and equations','Mole concept','Chemical reactions','Acids, bases and salts','Organic chemistry','Metals','Rates of reaction','Energy changes','Electrochemistry','Qualitative analysis'],
'Physics':['Measurement','Mechanics','Motion','Forces','Work, energy and power','Pressure','Heat','Waves','Light','Sound','Electricity','Magnetism','Electromagnetism','Atomic physics','Practical physics'],
'Biology':['Cells','Nutrition','Transport','Respiration','Excretion','Coordination','Reproduction','Genetics','Evolution','Ecology','Microorganisms','Health and diseases','Classification','Practical biology'],
'Civics':['Citizenship','Democracy','Human rights','Government','Constitution','Rule of law','Good governance','National identity','Gender','Culture','Globalisation','Environment'],
'Economics':['Basic economic concepts','Demand and supply','Elasticity','Production','Market structures','National income','Money and banking','Inflation','Unemployment','Public finance','International trade','Economic development'],
'Commerce':['Trade','Business units','Entrepreneurship','Banking','Insurance','Warehousing','Transport','Communication','Marketing','Consumer protection'],
'Bookkeeping':['Accounting concepts','Source documents','Double entry','Journals','Ledgers','Cash book','Trial balance','Bank reconciliation','Depreciation','Errors','Final accounts'],
'Agriculture':['Soils','Crop production','Crop pests and diseases','Livestock production','Animal nutrition','Farm tools','Farm management','Agricultural economics','Irrigation','Sustainable agriculture'],
'Computer Science':['Algorithms','Programming','Data structures','Databases','Computer architecture','Operating systems','Networks','Cybersecurity','Software engineering','Web technology'],
'Accountancy':['Accounting principles','Books of original entry','Ledgers','Trial balance','Final accounts','Partnership','Company accounts','Cost accounting','Financial analysis','Budgeting','Auditing'],
'Business Studies':['Entrepreneurship','Business environment','Management','Marketing','Finance','Human resources','Production','Trade','Business law','Business planning'],
'Computer Applications':['Office applications','Data management','Presentations','Spreadsheets','Word processing','Internet','Digital communication','Information management']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=s=>s.level+'::'+s.name;
const get=k=>subjects.find(s=>key(s)===k)||subjects[0];
function toast(t){const e=document.querySelector('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__vanesToast);window.__vanesToast=setTimeout(()=>e.classList.remove('show'),2400)}
window.showToast=window.showToast||toast;
function view(id){document.querySelectorAll('.view').forEach(e=>e.classList.toggle('active',e.id===id));document.querySelectorAll('.nav-link').forEach(e=>e.classList.toggle('active',e.dataset.view===id));document.querySelector('.sidebar')?.classList.remove('open');window.scrollTo(0,0);location.hash=id}
window.VANES_SWITCH_VIEW=view;
function renderSubjects(filter='all'){const g=document.querySelector('#subjectGrid');if(!g)return;const list=filter==='all'?subjects:subjects.filter(s=>s.level===filter);g.innerHTML=list.map(s=>`<article class="panel subject-card" tabindex="0" data-subject="${esc(key(s))}"><div class="subject-top"><span class="subject-icon">✦</span><span class="pill">${esc(s.level)}</span></div><h2>${esc(s.name)}</h2><p>${esc(s.lesson)}</p><div class="subject-progress"><div><span style="width:0%"></span></div>0%</div></article>`).join('');g.querySelectorAll('[data-subject]').forEach(e=>{const open=()=>openSubject(e.dataset.subject);e.addEventListener('click',open);e.addEventListener('keydown',x=>{if(x.key==='Enter'||x.key===' ')open()})})}
function renderDashboard(){const b=document.querySelector('#dashboardSubjects');if(!b)return;const list=[...subjects].sort((a,z)=>a.level.localeCompare(z.level)).slice(0,8);b.innerHTML=list.map(s=>`<article class="topic" tabindex="0" data-subject="${esc(key(s))}"><span class="topic-icon">✦</span><div><strong>${esc(s.name)}</strong><p>${esc(s.level)} · ${esc(s.lesson)}</p></div><span class="topic-arrow">→</span></article>`).join('');b.querySelectorAll('[data-subject]').forEach(e=>{const open=()=>openSubject(e.dataset.subject);e.addEventListener('click',open);e.addEventListener('keydown',x=>{if(x.key==='Enter'||x.key===' ')open()})})}
function openSubject(k){const s=get(k);document.querySelector('#workspaceLabel').textContent=`${s.name.toUpperCase()} · ${s.level}`;document.querySelector('#workspaceTitle').textContent=s.name;document.querySelector('#workspaceDescription').textContent=s.description;document.querySelector('#sessionTitle').textContent=`Start with ${s.lesson}`;const map=document.querySelector('#topicMap');if(map)map.innerHTML=(topics[s.name]||[s.lesson]).map(t=>`<button class="topic-chip" type="button" data-topic="${esc(t)}">${esc(t)}</button>`).join('');document.querySelector('#sessionSteps').innerHTML=['Recall what you already know.','Learn the core idea with a worked example.','Attempt practice questions without looking at the answer.','Summarise the lesson and identify one weak point.'].map(x=>`<li>${x}</li>`).join('');const n=document.querySelector('#notes');if(n)n.value=localStorage.getItem('vanes-notes-'+k)||'';view('workspace')}
function profile(){const n=localStorage.getItem('vanes-user-name');const name=n||'Student';const p=document.querySelector('#profileName'),a=document.querySelector('#profileAvatar'),w=document.querySelector('#welcomeTitle');if(p)p.textContent=name;if(a)a.textContent=name.charAt(0).toUpperCase();if(w)w.textContent=n?`Make today count, ${name}.`:'Make today count.';const m=document.querySelector('#nameModal');if(n){m?.classList.remove('show');m?.setAttribute('aria-hidden','true')}else{m?.classList.add('show');m?.setAttribute('aria-hidden','false')}}
function init(){
 document.querySelectorAll('[data-view]').forEach(e=>e.addEventListener('click',x=>{x.preventDefault();view(e.dataset.view)}));
 document.querySelectorAll('[data-view-target]').forEach(e=>e.addEventListener('click',()=>view(e.dataset.viewTarget)));
 document.querySelector('#mobileMenu')?.addEventListener('click',()=>document.querySelector('.sidebar')?.classList.toggle('open'));
 document.querySelectorAll('.filter-button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSubjects(b.dataset.filter)}));
 document.querySelector('#nameForm')?.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#nameInput'),n=input?.value.trim();if(!n)return;localStorage.setItem('vanes-user-name',n);profile();toast(`Welcome to VANES, ${n}.`)});
 document.querySelector('#changeName')?.addEventListener('click',()=>{const m=document.querySelector('#nameModal');m?.classList.add('show');m?.setAttribute('aria-hidden','false');const i=document.querySelector('#nameInput');if(i){i.value=localStorage.getItem('vanes-user-name')||'';i.focus()}});
 document.querySelector('#planForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),subject=String(f.get('subject')||'Study'),goal=String(f.get('goal')||'Learn'),time=Number(f.get('time')||45),a=Math.max(5,Math.round(time*.2)),b=Math.max(10,Math.round(time*.5)),c=Math.max(5,time-a-b);const r=document.querySelector('#planResult');if(!r)return;r.classList.add('generated');r.innerHTML=`<p class="eyebrow">${time}-MINUTE FOCUS SESSION</p><h2>${esc(subject)}</h2><p>Goal: ${esc(goal.toLowerCase())}.</p><ul><li><strong>${a} min — Recall:</strong> write what you already know.</li><li><strong>${b} min — Deep work:</strong> learn, solve and check examples.</li><li><strong>${c} min — Review:</strong> close your notes and explain the idea from memory.</li></ul><button class="primary-button" id="startPlan">Start this session →</button>`;document.querySelector('#startPlan')?.addEventListener('click',()=>{const s=subjects.find(x=>x.name.toLowerCase()===subject.toLowerCase());s?openSubject(key(s)):view('coach')})});
 const notes=document.querySelector('#notes'),status=document.querySelector('#saveStatus');notes?.addEventListener('input',()=>{const label=document.querySelector('#workspaceTitle')?.textContent||'current';localStorage.setItem('vanes-notes-'+label,notes.value);if(status)status.textContent='Saved locally'});document.querySelector('#clearNotes')?.addEventListener('click',()=>{if(notes)notes.value='';if(status)status.textContent='Notes cleared'});
 document.querySelector('#completeSession')?.addEventListener('click',()=>{toast('Session marked complete ✓');const stat=document.querySelector('#minutesStat');if(stat)stat.textContent='147 min'});
 document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{view('coach');const i=document.querySelector('#chatInput');if(i){i.value=b.dataset.prompt;i.focus()}}));
 renderSubjects();renderDashboard();profile();
 const hash=location.hash.slice(1);if(['dashboard','subjects','planner','coach'].includes(hash))view(hash);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
