/* VANES learner profile: level, combination and subject-specific study context. */
(function(){
'use strict';
const PROFILE='vanes-learner-profile-v1';
const O_LEVEL=['Kiswahili','English Language','Basic Mathematics','Basic Applied Mathematics','History','Geography','Chemistry','Physics','Biology','Civics','Information and Computer Studies','Commerce','Bookkeeping','Agriculture','Food and Nutrition','Fine Art','Music','French','Arabic','Bible Knowledge','Islamic Knowledge','Physical Education','Economics'];
const COMBOS={
 PCM:['Physics','Chemistry','Advanced Mathematics'], PCB:['Physics','Chemistry','Biology'], PGM:['Physics','Geography','Advanced Mathematics'], CBG:['Chemistry','Biology','Geography'], CBA:['Chemistry','Biology','Advanced Mathematics'], CBN:['Chemistry','Biology','Nutrition'], EGM:['Economics','Geography','Advanced Mathematics'], ECA:['Economics','Commerce','Advanced Mathematics'], HGE:['History','Geography','Economics'], HGL:['History','Geography','Kiswahili'], HKL:['History','Kiswahili','English Language'], HKA:['History','Kiswahili','Arabic'], HEC:['History','Economics','Commerce'], HGLi:['History','Geography','English Language']
};
function read(){try{return JSON.parse(localStorage.getItem(PROFILE))||null}catch{return null}}
function write(v){localStorage.setItem(PROFILE,JSON.stringify(v));localStorage.setItem('vanes-user-name',v.name)}
function selected(){const p=read();return p?.level==='A-Level'?(COMBOS[p.combination]||p.subjects||[]):(p?.subjects||O_LEVEL)}
function style(){if(document.getElementById('vanes-profile-style'))return;const s=document.createElement('style');s.id='vanes-profile-style';s.textContent='.profile-fields{display:grid;gap:12px;margin:14px 0}.profile-fields label{display:grid;gap:6px;text-align:left;font-size:13px;font-weight:700}.profile-fields select,.profile-fields input{width:100%;padding:12px;border:1px solid #d8dbe3;border-radius:12px;background:#fff;color:#111;font:inherit}.profile-subjects{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;max-height:190px;overflow:auto;padding:4px}.profile-subjects label{display:flex!important;grid-template-columns:none!important;align-items:center;gap:7px;background:#fff;border:1px solid #e2e4ea;border-radius:10px;padding:8px;font-weight:600;font-size:12px}.profile-subjects input{width:auto!important}.profile-context-badge{margin-top:8px;font-size:12px;opacity:.8}.subject-card.vanes-unselected{opacity:.42;filter:saturate(.55)}.subject-card.vanes-selected{outline:2px solid currentColor;outline-offset:-2px}.subject-card .vanes-specific-badge{font-size:11px;font-weight:700;margin-top:7px;opacity:.8}@media(max-width:560px){.profile-subjects{grid-template-columns:1fr}}
';document.head.appendChild(s)}
function build(){const modal=document.querySelector('#nameModal'),card=modal?.querySelector('.name-card'),form=document.querySelector('#nameForm');if(!card||!form)return;style();let fields=card.querySelector('.profile-fields');if(!fields){fields=document.createElement('div');fields.className='profile-fields';form.querySelector('input')?.remove();fields.innerHTML=`<label>Full name<input id="nameInput" required maxlength="40" placeholder="Your name" autocomplete="name"></label><label>Education level<select id="profileLevel" required><option value="">Choose your level</option><option value="O-Level">O-Level / CSEE</option><option value="A-Level">Advanced / A-Level</option></select></label><div id="profileChoice"></div>`;form.insertBefore(fields,form.querySelector('button'));}const level=document.querySelector('#profileLevel'),choice=document.querySelector('#profileChoice');function renderChoice(){if(!choice)return;if(level.value==='A-Level'){choice.innerHTML=`<label>Combination<select id="profileCombination" required><option value="">Choose your combination</option>${Object.keys(COMBOS).map(k=>`<option value="${k}">${k} — ${COMBOS[k].join(' + ')}</option>`).join('')}<option value="OTHER">Other combination</option></select></label><div class="profile-context-badge">Historia ya Tanzania and Academic Communication are included for every Advanced Level learner.</div>`}else if(level.value==='O-Level'){choice.innerHTML=`<label>Choose the subjects you take</label><div class="profile-subjects">${O_LEVEL.map(s=>`<label><input type="checkbox" name="profileSubject" value="${s}"> ${s}</label>`).join('')}</div>`}else choice.innerHTML='';}level?.addEventListener('change',renderChoice);form.addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#nameInput')?.value.trim();const lv=level?.value;if(!name||!lv)return;let subjects=[];let combination='';if(lv==='A-Level'){combination=document.querySelector('#profileCombination')?.value||'OTHER';subjects=COMBOS[combination]||[]}else{subjects=[...document.querySelectorAll('input[name="profileSubject"]:checked')].map(x=>x.value);if(!subjects.length){alert('Choose at least one O-Level subject so VANES can personalise your learning.');return}}write({name,level:lv,combination,subjects,updatedAt:new Date().toISOString()});modal.classList.remove('show');modal.setAttribute('aria-hidden','true');applyProfile();window.showToast?.(`Profile saved · ${lv}${combination?` · ${combination}`:''}`);},true);}
function applyProfile(){const p=read();if(!p)return;const name=document.querySelector('#profileName'),avatar=document.querySelector('#profileAvatar'),welcome=document.querySelector('#welcomeTitle');if(name)name.textContent=p.name;if(avatar)avatar.textContent=p.name.charAt(0).toUpperCase();if(welcome)welcome.textContent=`Welcome back, ${p.name}.`;document.body.dataset.vanesLevel=p.level;document.body.dataset.vanesCombination=p.combination||'';const wanted=new Set(selected().map(x=>x.toLowerCase()));document.querySelectorAll('#subjectGrid .subject-card').forEach(c=>{const h=c.querySelector('h2')?.textContent.trim();if(!h)return;const cardLevel=c.querySelector('.pill')?.textContent.trim();const applies=p.level==='A-Level'?cardLevel==='A-Level':cardLevel==='O-Level';const common=p.level==='A-Level'&&(h==='Historia ya Tanzania'||h==='Academic Communication');const onList=wanted.has(h.toLowerCase())||common;c.classList.toggle('vanes-selected',applies&&onList);c.classList.toggle('vanes-unselected',applies&&!onList);const old=c.querySelector('.vanes-specific-badge');if(old)old.remove();if(applies){const b=document.createElement('div');b.className='vanes-specific-badge';b.textContent=onList?'✓ In your study profile':'Not in your selected profile';c.appendChild(b)}});const sub=document.querySelector('#subjects .subtle');if(sub)sub.textContent=p.level==='A-Level'?`Showing the Advanced curriculum. ${p.combination||'Your combination'} is selected; Historia ya Tanzania and Academic Communication are common to all combinations.`:`Showing the O-Level curriculum. Your selected subjects are highlighted so VANES can focus its guidance on what you study.`}
function openExisting(){const p=read();const modal=document.querySelector('#nameModal');if(!p){modal?.classList.add('show');modal?.setAttribute('aria-hidden','false');}else applyProfile()}
function boot(){build();openExisting();const grid=document.querySelector('#subjectGrid');if(grid)new MutationObserver(()=>applyProfile()).observe(grid,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('#changeName')){const m=document.querySelector('#nameModal');m?.classList.add('show');m?.setAttribute('aria-hidden','false');const p=read();if(p){const n=document.querySelector('#nameInput');if(n)n.value=p.name;const l=document.querySelector('#profileLevel');if(l){l.value=p.level;l.dispatchEvent(new Event('change'));setTimeout(()=>{const c=document.querySelector('#profileCombination');if(c)c.value=p.combination||'';p.subjects.forEach(s=>{const x=document.querySelector(`input[name="profileSubject"][value="${CSS.escape(s)}"]`);if(x)x.checked=true})},0)}}}},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
